### ISSUE TITLE
Add terraform to deploy a lambda

### ISSUE THREAD

**Issue by itsdalmo** [telia-oss/sidecred#1]
Need to add a `terraform/` directory with a module that allows us to easily deploy a Lambda version of `sidecred`.

**Comment by jhosteny** [comment]
@itsdalmo we are using our own terraform for this, but I thought I would point out that I have found it easier to allow role assumptions based on [tagging](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam-assume-tagged-role.html). That way, there are no requirements on the role names.

**Comment by itsdalmo** [comment]
Thats a great tip @jhosteny - thanks! I'll include it when I get around to the terraform again 👍

**Comment by itsdalmo** [comment]
We have added a terraform module here:
https://github.com/telia-oss/terraform-aws-sidecred
