### ISSUE TITLE
Add method to retrieve GH private key from store or backend

### ISSUE THREAD

**Issue by jhosteny** [telia-oss/sidecred#11]
Hi @itsdalmo - the lambda enabled version of the code requires the GH private key to be loaded from a file. It could be read from an encrypted bucket, SSM or Secrets Manager.

It seems like it would be reasonable to require that it be stored in SSM or Secrets Manager. I'm happy to work on a PR if you have a desired direction here?

**Comment by itsdalmo** [comment]
Hey again! My thinking on this was that we could use [aws-env](https://github.com/telia-oss/aws-env) in the Lambda version of `sidecred` to load credentials from either SSM or secrets manager (or just KMS decrypting it).

We are already doing this for the STS and/or Github Lambdas, and it has been working great so far. What do you think?

**Comment by jhosteny** [comment]
@itsdalmo oops, I missed aws-env. That will be perfect.

I'll take a stab at this. Don't worry about responding on your vacation. I will just use my fork for now.
