### ISSUE TITLE
Add Rotation Override to CredentialRequests

### ISSUE THREAD

**Issue by joelholmes** [telia-oss/sidecred#57]
In issue https://github.com/telia-oss/sidecred/issues/22, a solution was added to change the rotation window for credentials. However, we've encountered situations where we wished to be a little more granular with our rotation configuration. Having a default rotation window will help in most cases however we have certain credentials that we would want to shrink the window for but leave others as the default. I believe adding an optional value to the `CredentialRequest` and checking in the `hasValidCredentials` method should handle this case. 

I am testing a solution locally but wanted to see if there were any major scenarios I may be missing or if there are any recommendations for approaching this.

**Comment by itsdalmo** [comment]
Closed by #58.
