### ISSUE TITLE
Add support for GH app token naming

### ISSUE THREAD

**Issue by ian1780** [telia-oss/sidecred#76]
Concourse's integration with AWS Secrets Manager's integration relies on a specific path template: "/concourse/{{ .Namespace }}/{{ .Name }}". However, this makes it difficult for multiple teams to use the same sidecred-lambda function due to the Namespace needing to be different (e.g., team A and team B are different teams in Concourse and are unable to use different tokens generated by one sidecred-lambda function since the Namespace is part of the default path and the token name is partially hardcoded).

Unless there is a workaround, it would be nice to be able to specify the name of the Github App Token to be generated so that one can set the secret_template to be "/concourse/{{ .Name }}" and just name the token as "team_name/token_name".

When token_name is not specified in the config file, everything would still function the same and the token would be named the default method.

**Comment by itsdalmo** [comment]
Hi! Saw you got your fix merged, but just wanted to mention that "namespace" essentially translates to a team. So the thinking is that each team has their own Sidecred config, and you use one Lambda with multiple CRON schedules (one per config) to process the various configs.

You can use the `telia-oss/terraform-aws-sidecred` terraform module to set this up👍

**Comment by ian1780** [comment]
Hmm, I never knew that multiple config files could be used for one function. Hopefully the token name addition is still a good addition :)
